CREATE TABLE tb_pm200_bs2 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_cc1 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_cc234 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_chab (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm200_chcd (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm200_chef (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm200_chsaa (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm200_chsab (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm200_chsac (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm200_conn (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_cr1 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_cr2 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_cr3 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_cr4 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_cr5 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_cr6 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_cr7 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_cr8 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_cr9 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_cr10 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_cr11 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_cr12 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;








CREATE TABLE tb_pm200_ct (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_hla (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_ra (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_ret (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm200_weng (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_bs1 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_bs2 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_cc1 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_cc234 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_chab (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;




CREATE TABLE tb_pm220_chcd (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_chef (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_chsaa (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_chsab (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_chsac (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_conn (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_cr1 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_cr2 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm220_cr3 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm220_cr4 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm220_cr5 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm220_cr6 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm220_cr7 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm220_cr8 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm220_cr9 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm220_cr10 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm220_cr11 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


CREATE TABLE tb_pm220_cr12 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;



CREATE TABLE tb_pm220_ct (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_hla (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_lpf3 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_ra (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_pm220_ret (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    power_meter VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    shift VARCHAR(50) NOT NULL,
    day VARCHAR(50) NOT NULL,
    week VARCHAR(50) NULL DEFAULT NULL,
    month VARCHAR(50) NULL DEFAULT NULL,
    year VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;





















