CREATE TABLE balance_shaft_no_1 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE balance_shaft_no_2 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;





CREATE TABLE cam_cap (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE cam_cap_1 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE cam_cap_1a (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE cam_cap_1b (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE cam_cap_1c_d05e (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE cam_cap_1c_nr (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE cam_cap_2 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE cam_cap_3 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE cam_cap_4 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE cam_housing (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE cam_housing_a (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE cam_housing_assy (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE cam_housing_assy_a (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE cam_housing_assy_b (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE cam_housing_assy_c_d05e (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE cam_housing_assy_c_nr (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE cam_housing_b (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE cam_housing_c (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE cam_housing_d (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE cam_housing_e_d05e (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE cam_housing_e_nr (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE common_rail_1 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;



CREATE TABLE common_rail_2 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE common_rail_3 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE common_rail_4 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE common_rail_5 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE common_rail_6 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE common_rail_7 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE common_rail_8 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE common_rail_9 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE common_rail_10 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE common_rail_11 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE common_rail_12 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE connector (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;



CREATE TABLE drive_gear (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;



CREATE TABLE housing_inlet_d13e (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;





CREATE TABLE housing (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE housing_inlet_tr (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;



CREATE TABLE housing_inlet_water (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;



CREATE TABLE hydraulic_lash_adjuster (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;



CREATE TABLE Main_data (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;



CREATE TABLE packing_assy_a (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE packing_assy_b (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE packing_assy_c (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE production_data (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE production_data_trial (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;



CREATE TABLE retainer (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;



CREATE TABLE roller_arm_1 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE roller_arm_1_a (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE roller_arm_1_b (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;



CREATE TABLE roller_arm_1_c (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE roller_arm_1_d (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE roller_arm_1_e (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE roller_arm_2 (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE roller_arm_2_a (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;




CREATE TABLE roller_arm_2_b (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;



CREATE TABLE roller_arm_2_c (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;

CREATE TABLE roller_arm_2_d (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;



CREATE TABLE roller_arm_2_e (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;


CREATE TABLE spacer_drive_gear (
    idPrimary INT(11) NOT NULL AUTO_INCREMENT,
    line_id VARCHAR(10) NULL DEFAULT NULL,
    pg VARCHAR(10) NULL DEFAULT NULL,
    line_name VARCHAR(50) NULL DEFAULT NULL,
    name_product VARCHAR(100) NULL DEFAULT NULL,
    target VARCHAR(50) NULL DEFAULT NULL,
    actual VARCHAR(50) NULL DEFAULT NULL,
    loading_time VARCHAR(50) NULL DEFAULT NULL,
    efficiency VARCHAR(50) NULL DEFAULT NULL,
    delay VARCHAR(50) NULL DEFAULT NULL,
    cycle_time VARCHAR(50) NULL DEFAULT NULL,
    status VARCHAR(50) NULL DEFAULT NULL,
    time_trouble VARCHAR(50) NULL DEFAULT NULL,
    time_trouble_quality VARCHAR(50) NULL DEFAULT NULL,
    andon VARCHAR(50) NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idPrimary)
) ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_general_ci;





















