CREATE TABLE tb_realtime_comp_19 (
    id INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Waktu pencatatan',
    current_avg_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Rata-rata (A)',
    frequency_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Frekuensi (Hz)',
    apparent_power_a_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa A (kVA)',
    active_power_a_ext DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa A (kW)',
    reactive_power_a_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa A (kVAR)',
    power_factor_a_ext DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa A',
    voltage_ab_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line A-B (V)',
    voltage_an_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Fasa A-N (V)',
    current_a_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa A (A)',
    apparent_power_b_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa B (kVA)',
    active_power_b_ext DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa B (kW)',
    reactive_power_b_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa B (kVAR)',
    power_factor_b_ext DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa B',
    voltage_bc_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line B-C (V)',
    voltage_bn_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Fasa B-N (V)',
    current_b_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa B (A)',
    apparent_power_c_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa C (kVA)',
    active_power_c_ext DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa C (kW)',
    reactive_power_c_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa C (kVAR)',
    power_factor_c_ext DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa C',
    voltage_ca_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line C-A (V)',
    voltage_cn_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Fasa C-N (V)',
    current_c_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa C (A)',
    fwdVAh_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Semu Forward (kVAh)',
    fwdWh_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Aktif Forward (kWh)',
    fwdVARh_ind_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Reaktif Induktif Forward (kVARh)',
    fwdVARh_cap_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Reaktif Kapasitif Forward (kVARh)',
    revVAh_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Semu Reverse (kVAh)',
    revWh_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Aktif Reverse (kWh)',
    revVARh_ind_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Reaktif Induktif Reverse (kVARh)',
    revVARh_cap_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Reaktif Kapasitif Reverse (kVARh)',
    present_demand_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Demand Saat Ini',
    rising_demand_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Demand Maksimum',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tabel data eksternal KUB';

CREATE TABLE tb_realtime_comp_21 (
    id INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Waktu pencatatan',
    current_avg_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Rata-rata (A)',
    frequency_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Frekuensi (Hz)',
    apparent_power_a_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa A (kVA)',
    active_power_a_ext DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa A (kW)',
    reactive_power_a_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa A (kVAR)',
    power_factor_a_ext DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa A',
    voltage_ab_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line A-B (V)',
    voltage_an_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Fasa A-N (V)',
    current_a_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa A (A)',
    apparent_power_b_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa B (kVA)',
    active_power_b_ext DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa B (kW)',
    reactive_power_b_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa B (kVAR)',
    power_factor_b_ext DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa B',
    voltage_bc_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line B-C (V)',
    voltage_bn_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Fasa B-N (V)',
    current_b_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa B (A)',
    apparent_power_c_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa C (kVA)',
    active_power_c_ext DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa C (kW)',
    reactive_power_c_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa C (kVAR)',
    power_factor_c_ext DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa C',
    voltage_ca_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line C-A (V)',
    voltage_cn_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Fasa C-N (V)',
    current_c_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa C (A)',
    fwdVAh_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Semu Forward (kVAh)',
    fwdWh_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Aktif Forward (kWh)',
    fwdVARh_ind_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Reaktif Induktif Forward (kVARh)',
    fwdVARh_cap_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Reaktif Kapasitif Forward (kVARh)',
    revVAh_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Semu Reverse (kVAh)',
    revWh_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Aktif Reverse (kWh)',
    revVARh_ind_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Reaktif Induktif Reverse (kVARh)',
    revVARh_cap_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Reaktif Kapasitif Reverse (kVARh)',
    present_demand_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Demand Saat Ini',
    rising_demand_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Demand Maksimum',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tabel data eksternal KUB';


CREATE TABLE tb_realtime_comp_24 (
    id INT(11) NOT NULL AUTO_INCREMENT,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Waktu pencatatan',
    current_avg_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Rata-rata (A)',
    frequency_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Frekuensi (Hz)',
    apparent_power_a_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa A (kVA)',
    active_power_a_ext DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa A (kW)',
    reactive_power_a_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa A (kVAR)',
    power_factor_a_ext DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa A',
    voltage_ab_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line A-B (V)',
    voltage_an_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Fasa A-N (V)',
    current_a_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa A (A)',
    apparent_power_b_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa B (kVA)',
    active_power_b_ext DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa B (kW)',
    reactive_power_b_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa B (kVAR)',
    power_factor_b_ext DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa B',
    voltage_bc_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line B-C (V)',
    voltage_bn_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Fasa B-N (V)',
    current_b_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa B (A)',
    apparent_power_c_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa C (kVA)',
    active_power_c_ext DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa C (kW)',
    reactive_power_c_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa C (kVAR)',
    power_factor_c_ext DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa C',
    voltage_ca_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line C-A (V)',
    voltage_cn_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Fasa C-N (V)',
    current_c_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa C (A)',
    fwdVAh_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Semu Forward (kVAh)',
    fwdWh_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Aktif Forward (kWh)',
    fwdVARh_ind_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Reaktif Induktif Forward (kVARh)',
    fwdVARh_cap_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Reaktif Kapasitif Forward (kVARh)',
    revVAh_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Semu Reverse (kVAh)',
    revWh_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Aktif Reverse (kWh)',
    revVARh_ind_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Reaktif Induktif Reverse (kVARh)',
    revVARh_cap_ext DECIMAL(20,3) NULL DEFAULT NULL COMMENT 'Energi Reaktif Kapasitif Reverse (kVARh)',
    present_demand_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Demand Saat Ini',
    rising_demand_ext DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Demand Maksimum',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tabel data eksternal KUB';








CREATE TABLE tb_realtime_kubikal (
    id TINYINT(1) NOT NULL DEFAULT 1,
    date_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Waktu pencatatan',
    panel VARCHAR(50) COLLATE utf8mb4_uca1400_ai_ci NULL DEFAULT NULL COMMENT 'Nama panel',
    current_avg DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Rata-rata (A)',
    current_a DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa A (A)',
    current_b DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa B (A)',
    current_c DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa C (A)',
    current_n DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Netral (A)',
    active_power_total DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Total (kW)',
    active_power_a DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa A (kW)',
    active_power_b DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa B (kW)',
    active_power_c DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa C (kW)',
    apparent_power_total DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Total (kVA)',
    apparent_power_a DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa A (kVA)',
    apparent_power_b DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa B (kVA)',
    apparent_power_c DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa C (kVA)',
    data_freq DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Frekuensi (Hz)',
    power_factor_total DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Total',
    power_factor_a DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa A',
    power_factor_b DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa B',
    power_factor_c DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa C',
    reactive_power_total DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Total (kVAR)',
    reactive_power_a DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa A (kVAR)',
    reactive_power_b DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa B (kVAR)',
    reactive_power_c DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa C (kVAR)',
    voltage_ll_avg DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Rata-rata Line-to-Line (V)',
    voltage_ab DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Line Fasa A-B (V)',
    voltage_bc DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Line Fasa B-C (V)',
    voltage_ca DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Line Fasa C-A (V)',
    voltage_ln_avg DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Rata-rata Line-to-Neutral (V)',
    voltage_an DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Neutral Fasa A-N (V)',
    voltage_bn DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Neutral Fasa B-N (V)',
    voltage_cn DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Neutral Fasa C-N (V)',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tb_realtime_kubikal_p63 (
    id TINYINT(1) NOT NULL DEFAULT 1,
    date_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Waktu pencatatan',
    panel VARCHAR(50) COLLATE utf8mb4_uca1400_ai_ci NULL DEFAULT NULL COMMENT 'Nama panel',
    current_avg DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Rata-rata (A)',
    current_a DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa A (A)',
    current_b DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa B (A)',
    current_c DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa C (A)',
    current_n DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Netral (A)',
    active_power_total DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Total (kW)',
    active_power_a DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa A (kW)',
    active_power_b DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa B (kW)',
    active_power_c DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa C (kW)',
    apparent_power_total DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Total (kVA)',
    apparent_power_a DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa A (kVA)',
    apparent_power_b DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa B (kVA)',
    apparent_power_c DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa C (kVA)',
    data_freq DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Frekuensi (Hz)',
    power_factor_total DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Total',
    power_factor_a DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa A',
    power_factor_b DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa B',
    power_factor_c DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa C',
    reactive_power_total DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Total (kVAR)',
    reactive_power_a DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa A (kVAR)',
    reactive_power_b DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa B (kVAR)',
    reactive_power_c DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa C (kVAR)',
    voltage_ll_avg DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Rata-rata Line-to-Line (V)',
    voltage_ab DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Line Fasa A-B (V)',
    voltage_bc DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Line Fasa B-C (V)',
    voltage_ca DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Line Fasa C-A (V)',
    voltage_ln_avg DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Rata-rata Line-to-Neutral (V)',
    voltage_an DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Neutral Fasa A-N (V)',
    voltage_bn DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Neutral Fasa B-N (V)',
    voltage_cn DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Neutral Fasa C-N (V)',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tabel pengukuran KUB lengkap';


CREATE TABLE tb_realtime_kubikal_p64 (
    id TINYINT(1) NOT NULL DEFAULT 1,
    date_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Waktu pencatatan',
    panel VARCHAR(50) COLLATE utf8mb4_uca1400_ai_ci NULL DEFAULT NULL COMMENT 'Nama panel',
    current_avg DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Rata-rata (A)',
    current_a DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa A (A)',
    current_b DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa B (A)',
    current_c DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Fasa C (A)',
    current_n DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Arus Netral (A)',
    active_power_total DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Total (kW)',
    active_power_a DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa A (kW)',
    active_power_b DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa B (kW)',
    active_power_c DECIMAL(12,3) NULL DEFAULT NULL COMMENT 'Daya Aktif Fasa C (kW)',
    apparent_power_total DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Total (kVA)',
    apparent_power_a DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa A (kVA)',
    apparent_power_b DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa B (kVA)',
    apparent_power_c DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Semu Fasa C (kVA)',
    data_freq DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Frekuensi (Hz)',
    power_factor_total DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Total',
    power_factor_a DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa A',
    power_factor_b DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa B',
    power_factor_c DECIMAL(5,3) NULL DEFAULT NULL COMMENT 'Faktor Daya Fasa C',
    reactive_power_total DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Total (kVAR)',
    reactive_power_a DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa A (kVAR)',
    reactive_power_b DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa B (kVAR)',
    reactive_power_c DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Daya Reaktif Fasa C (kVAR)',
    voltage_ll_avg DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Rata-rata Line-to-Line (V)',
    voltage_ab DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Line Fasa A-B (V)',
    voltage_bc DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Line Fasa B-C (V)',
    voltage_ca DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Line Fasa C-A (V)',
    voltage_ln_avg DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Rata-rata Line-to-Neutral (V)',
    voltage_an DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Neutral Fasa A-N (V)',
    voltage_bn DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Neutral Fasa B-N (V)',
    voltage_cn DECIMAL(10,3) NULL DEFAULT NULL COMMENT 'Tegangan Line-to-Neutral Fasa C-N (V)',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tabel pengukuran KUB lengkap';
